// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Twtr.UrlShortener.Persistence;

#nullable disable

namespace Twtr.UrlShortener.Persistence.Migrations
{
    [DbContext(typeof(UrlShortenerContext))]
    [Migration("20240322160556_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Twtr.UrlShortener.Persistence.TLDEntity", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeedNumber")
                        .HasColumnType("int");

                    b.Property<string>("TLD")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TLDs");
                });

            modelBuilder.Entity("Twtr.UrlShortener.Persistence.UrlShortener.UrlEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortenedUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("TLDId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TLDId", "ShortenedUrl" }, "IX_TLDId_ShortenedUrl")
                        .IsUnique()
                        .HasFilter("[TLDId] IS NOT NULL AND [ShortenedUrl] IS NOT NULL");

                    b.ToTable("Urls");
                });

            modelBuilder.Entity("Twtr.UrlShortener.Persistence.UrlShortener.UrlEntity", b =>
                {
                    b.HasOne("Twtr.UrlShortener.Persistence.TLDEntity", "TLDEntity")
                        .WithMany()
                        .HasForeignKey("TLDId");

                    b.Navigation("TLDEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
